project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    - "posts/**/*.qmd"
website:
  description: "A blog built with Quarto"
  site-url: https://leonardoalva98.github.io/senior_project/ # you must change this appropriately for RSS feeds to work properly
  title: "Leo Alvarino Senior Project"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/leonardoalva98
      - icon: linkedin  
        href: https://www.linkedin.com/in/leonardoalva98/
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css



